<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCGLEbmQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCGLEbmQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCGLEbmQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCGLEbmQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCGLEbmQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CGLEbmQ',
    'container.build_id' => '2f5a84ca',
    'container.build_time' => 1573941200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCGLEbmQ');
