<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxYxsgi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxYxsgi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxYxsgi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxYxsgi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSxYxsgi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SxYxsgi',
    'container.build_id' => 'aa7f6253',
    'container.build_time' => 1573998557,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxYxsgi');
