<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxCbg3t\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxCbg3t/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxCbg3t.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxCbg3t\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSxCbg3t\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SxCbg3t',
    'container.build_id' => 'f2727709',
    'container.build_time' => 1573997921,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxCbg3t');
